### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by CRACKISH** [gretard/sonar-tsql-plugin#1]
**My config file:**

sonar.host.url=http://tscore-sonar:9000
sonar.login=admin
sonar.password=admin

sonar.projectKey=rootkey
sonar.projectName=rootname
sonar.projectVersion=1.0

sonar.working.directory=C:\\Projects\\sonar-scanner\\workdir\\

sonar.language=tsql

sonar.tsql.cg.reportPath=C:\\Projects\\sonar-scanner\\workdir\\
sonar.tsql.cg.report=cgresults.xml
sonar.tsql.ms.reportPath=C:\\Projects\\sonar-scanner\\workdir\\
sonar.tsql.ms.report=test.xml

#sonar.report.export.path=sonar-report.json
sonar.analysis.mode=preview
#sonar.issuesReport.json.enable=true

sonar.sourceEncoding=UTF-8

#sonar.exclusions=**/*_Tests.js

**My test sql:**

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_MytestsProcedure]'))
	DROP PROCEDURE [dbo].[sp_MytestsProcedure]
GO
CREATE PROCEDURE [dbo].[sp_MytestsProcedure]
AS
BEGIN
	select * from ProductType;
	
	declare @test varchar(max);
	
	select Name from ACCOUNT
		GROUP BY ALL;
END;

CREATE PROCEDURE [dbo].[sp_Get]
	@param1 int = 0,
	@param2 int
AS
	SELECT * FROM TestTable
RETURN 0

**My scanner log:**

C:\Projects\Storage\ALtest\SqlScripts\MyTestProcedure>sonar-scanner -Dsonar.sources=C:\Projects\Storage\ALtest\SqlScripts\MyTestProcedure\
C:\Projects\sonar-scanner\bin\..
INFO: Scanner configuration file: C:\Projects\sonar-scanner\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_111 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Users\A.Vanikhin\.sonar\cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=172ms
INFO: User cache: C:\Users\A.Vanikhin\.sonar\cache
INFO: Exclude plugins: devcockpit, buildstability, pdfreport, report, scmstats, buildbreaker, views, jira
INFO: Load plugins index
INFO: Load plugins index (done) | time=7ms
INFO: SonarQube server 6.0
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
WARN: Project doesn't exist on the server. All issues will be marked as 'new'.
INFO: Load project repositories (done) | time=16ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=31ms
INFO: Load active rules
INFO: Load active rules (done) | time=266ms
INFO: Issues mode
INFO: Scanning only changed files
INFO: -------------  Scan rootname
INFO: Language is forced to tsql
INFO: Load server rules
INFO: Load server rules (done) | time=187ms
INFO: Base dir: C:\Projects\Storage\ALtest\SqlScripts\MyTestProcedure
INFO: Working dir: C:\Projects\sonar-scanner\workdir
INFO: Source paths: .
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: Excluded sources:
INFO:   **/EjCommonAll.js
INFO:   **/EjDiagram.js
INFO:   **/WebitelVerto.js
INFO:   **/WebitelJsSipLibrary.js
INFO:   **/Highcharts.js
INFO:   **/OktellModule.js
INFO:   **/Galleria.js
INFO: 2 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for tsql: T-SQL Rules
INFO: Sensor Coverage Report Import
INFO: Sensor Coverage Report Import (done) | time=16ms
INFO: Sensor Coverage Report Import
INFO: Sensor Coverage Report Import (done) | time=0ms
INFO: Sensor Unit Test Results Import
INFO: Sensor Unit Test Results Import (done) | time=0ms
INFO: Sensor XmlFileSensor
INFO: Sensor XmlFileSensor (done) | time=15ms
INFO: Sensor VisualStudioIssuesLoaderSensor
INFO: Sensor VisualStudioIssuesLoaderSensor (done) | time=0ms
INFO: Sensor SqlCodeGuardIssuesLoaderSensor
INFO: Sensor SqlCodeGuardIssuesLoaderSensor (done) | time=16ms
INFO: Performing issue tracking
INFO: 4/4 components tracked
INFO: ANALYSIS SUCCESSFUL
INFO: Task total time: 2.085 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 3.533s
INFO: Final Memory: 52M/269M
INFO: ------------------------------------------------------------------------

What is the problem?

**Comment by gretard** [comment]
Hi, did you find the problem?

**Comment by CRACKISH** [comment]
Hi) yes. I don't have sqlcodeguard ))) It would be nice to add to the description that sqlcodeguard requires.

**Comment by gretard** [comment]
Hi,
I have updated read me yesterday and updated code to run SQL Code guard automatically. So I hope  everything will be working for you :)
