### ISSUE TITLE
Error During SonarQube scanner Execution

### ISSUE THREAD

**Issue by AnandDivakaran** [gretard/sonar-tsql-plugin#14]
Can you please guide me on the below error when executing the following  ?
"path to scanner"\sonar-scanner -Dsonar.projectKey=SampleTSQL -Dsonar.sources="path to sql files"

![image](https://user-images.githubusercontent.com/7632016/36368051-8999f274-157b-11e8-9ef0-d239d8c5cfb5.png)

![image](https://user-images.githubusercontent.com/7632016/36368074-9afa1968-157b-11e8-9e6a-5920c8bfacaa.png)

**Comment by gretard** [comment]
Hi,

I was not able to reproduce the issue, but I would suggest trying to run analysis with sonar.projectBaseDir property:

sonar-scanner.bat -Dsonar.projectKey=SampleTSQL -Dsonar.sources=. -Dsonar.projectBaseDir="<absolute_path_to_sources>"

Please let me know if this helped to solve the issue.

**Comment by AnandDivakaran** [comment]
Thanks for the quick response. Assigning "sonar.projectBaseDir" a value resolved the issue
