### ISSUE TITLE
It is possible to implement the plugin in an instance linux

### ISSUE THREAD

**Issue by ederlazaro** [gretard/sonar-tsql-plugin#15]
The question is related to the SQL Code Guard tool CMD configuration.

I understand that the SQL Code Guard tool CMD must be installed on the same Sonar Qube server.

![image](https://user-images.githubusercontent.com/2934085/38562815-0bf6a324-3ca1-11e8-8255-25382a7a1c8d.png)

**Comment by gretard** [comment]
Hello,

As far as I know SQL Code guard is not able to be run on Linux. Otherwise, it would be possible to include findings. However, plugin itself has a few [custom rules](https://github.com/gretard/sonar-tsql-plugin/wiki/Plugin-rules) which works on Linux :)

**Comment by gretard** [comment]
Hi,

Yes, if you run your SonarQube server on Linux and execute analysis on Windows machine with SQL Code Guard installed - then everything should be fine. As SQL Code Guard path (sonar.tsql.cg.path) property is used by sonar scanner and not by SonarQube server. In addition to this, you can set property globally on SonarQube server in administration section or override it in your sonar sonar-project.properties file by setting sonar.tsql.cg.path property. 

Please let me know if this helps.
