### ISSUE TITLE
Unit Test Reporting

### ISSUE THREAD

**Issue by KroniKZA** [gretard/sonar-tsql-plugin#16]
Hi,

Is there any planned work for unit test reporting such as count and count coverage?

Thanks

**Comment by gretard** [comment]
Hello,

Thank you for you feature request. It would be possible, however it depends on the tools which run sql tests and measures coverage. Do you have anything particular in mind like SQLCover?

**Comment by KroniKZA** [comment]
Hi,

SQLCover would be the ideal option. Currently tests are being run with TSqlT and coverage reports being generated with SQLCover. 

Thanks

**Comment by gretard** [comment]
Hello, please take a look at [latest ](https://github.com/gretard/sonar-tsql-plugin/releases/tag/0.8.0) release of the plugin. A feature to report coverage has been added. But, it might need more proofing as coverage is run directly on server, while your source code might not be the same as reported by SQLCover.
