### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by CRACKISH** [gretard/sonar-tsql-plugin#2]
It would be nice if there was a search for doubles.

**Comment by gretard** [comment]
Hi, @CRACKISH  I updated code with code duplication and keyword support using grammar from https://github.com/antlr/grammars-v4/tree/master/tsql , however I haven't tested it on large codebase so there might be unexpected issues. You can check the [0.4.0-alpha](https://github.com/gretard/sonar-tsql-plugin/releases/tag/0.4.0-alpha) release with these features.
