### ISSUE TITLE
Duplication plugin identification key

### ISSUE THREAD

**Issue by jirkamlejnek** [gretard/sonar-tsql-plugin#20]
Thank you for this plugin. 
I have installed this plugin in SonarQube, and it works fine, but after I click on Update button in Administration-Marketplace than your plugin was overridden with the official commercial T-SQL plugin. 
Maybe would be better to change identification key of this plugin which will not be in a collision with this official plugin.

**Comment by gretard** [comment]
Thank you for raising this. I am aware of this, I am not sure about changing key as then this might introduce breaking changes.

**Comment by gretard** [comment]
Closing this was updated in the latest release (https://github.com/gretard/sonar-tsql-plugin/releases/tag/0.9.0)
