### ISSUE TITLE
WARN Message on sonar-scanner

### ISSUE THREAD

**Issue by enniob** [gretard/sonar-tsql-plugin#24]
I just ran sonar-scanner and I got this WARN message on the console.

WARN: Property 'sonar.tsql.customrules.paths' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.

**Comment by gretard** [comment]
Hi,

Thank you for reporting this :) Will fix this in the upcoming release.

Greta

**Comment by gretard** [comment]
Hi,

This has been fixed in the updated version of the new plugin at https://github.com/gretard/sonar-sql-plugin. It has same feature and bug fixes as this plugin and supports more languages as well.
