### ISSUE TITLE
Custom Rules with variable search parameter and debtRemediationFunctionCoefficient

### ISSUE THREAD

**Issue by tgov01** [gretard/sonar-tsql-plugin#26]
Is it possible to have a custom rule with variable search parameter... (textToFind).  What I'm looking to do is tie back a table's name to the parent name of the table being updated (Ddl_objectContext).  If the parent is being updated, skip the rule.  Basically, the rule is to look for tables not using "WITH (NOLOCK)".

Update T1
Set Col1 = T2.Col1
From dbo.Table1 T1 Inner Join dbo.Table2 T2 WITH (NOLOCK) 
  On T1.Col1 = T2.Col1

Basically, Table1 doesn't need the NOLOCK because it is being updated, but Table2 should use the NOLOCK table hint.

Additionally, I noticed that debtRemediationFunctionCoefficient is not working for me.  As I understand it, this is supposed to show the amount of work required to remediate the issue.  This is showing as "0min effort" even though that node is present.

    <remediationFunction>LINEAR</remediationFunction>
    <debtRemediationFunctionCoefficient>2min</debtRemediationFunctionCoefficient>

Thanks in advance for any help you could provide.

**Comment by gretard** [comment]
Hi,

Thank you for raising this. This plugin is no longer developed. You should
use https://github.com/gretard/sonar-sql-plugin instead. Anyway could you
provide full implementation of your rule? I am mostly interested in full
ruleImplementation part so that I could try to help you :)

Cheers,
Greta

**Comment by tgov01** [comment]
Thanks for getting back to me on this.  I believe that we are using the new plug-in.  I probably posted in the wrong forum.  Below is my full implementation of the rule.

<?xml version="1.0" encoding="utf-8"?>
<sql-rules repoName="SQL Rules" repoKey="SQL Analyzer" isAdhoc="true">
  <rule>
    <key>CC101</key>
    <name>Table without "WITH (NOLOCK)" hint used.</name>
    <internalKey>CC101</internalKey>
    <description>&lt;h2&gt;Description&lt;/h2&gt;&lt;p&gt;Table without "WITH (NOLOCK)" hint used.&lt;/p&gt;&lt;h2&gt;Code examples&lt;/h2&gt;&lt;h3&gt;Non-compliant&lt;/h3&gt;&lt;pre&gt;&lt;code&gt;SELECT DistributorID, FirstName, LastName From dbo.Distributor&lt;/code&gt;&lt;/pre&gt;&lt;h3&gt;Compliant&lt;/h3&gt;&lt;pre&gt;&lt;code&gt;SELECT DistributorID, FirstName, LastName From dbo.Distributor WITH (NOLOCK)&lt;/code&gt;&lt;/pre&gt;</description>
    <severity>BLOCKER</severity>
    <cardinality>SINGLE</cardinality>
    <remediationFunction>LINEAR</remediationFunction>
    <debtRemediationFunctionCoefficient>2min</debtRemediationFunctionCoefficient>
    <ruleImplementation>
      <names>
        <textItem>Table_source_itemContext</textItem>
      </names>
      <textToFind/>
      <parentRules>
        
        <ruleImplementation>
          <names>
            <textItem>Select_statementContext</textItem>
            <textItem>Delete_statementContext</textItem>
            <textItem>Update_statementContext</textItem>
            <textItem>Merge_statementContext</textItem>
            <textItem>Insert_statementContext</textItem>
          </names>
          <textToFind/>
          <ruleViolationMessage/>
          <ruleMatchType>ClassOnly</ruleMatchType>
          <ruleResultType>SkipIfNotFound</ruleResultType>
        </ruleImplementation>
      </parentRules>
      <childrenRules>
        
        <ruleImplementation>
          <names>
            <textItem>Table_name_with_hintContext</textItem>
          </names>
          <textToFind/>
          <ruleViolationMessage/>
          <ruleMatchType>ClassOnly</ruleMatchType>
          <ruleResultType>SkipIfNotFound</ruleResultType>
          <textCheckType>Default</textCheckType>
        </ruleImplementation>
        
        <ruleImplementation>
          <names>
            <textItem>Table_name_with_hintContext</textItem>
          </names>
          <textToFind>
            <textItem>#</textItem>
          </textToFind>
          <ruleViolationMessage/>
          <ruleMatchType>TextAndClass</ruleMatchType>
          <ruleResultType>SkipIfFound</ruleResultType>
          <textCheckType>Contains</textCheckType>
        </ruleImplementation>
        
        <ruleImplementation>
          <names>
            <textItem>SubqueryContext</textItem>
          </names>
          <textToFind/>
          <ruleViolationMessage/>
          <ruleMatchType>ClassOnly</ruleMatchType>
          <ruleResultType>SkipIfFound</ruleResultType>
        </ruleImplementation>
        <ruleImplementation>
          <names>
            <textItem>Table_hintContext</textItem>
          </names>
          <textToFind>
            <textItem>NOLOCK</textItem>
          </textToFind>
          <ruleViolationMessage/>
          <ruleMatchType>TextAndClass</ruleMatchType>
          <ruleResultType>FailIfNotFound</ruleResultType>
          <textCheckType>Contains</textCheckType>
        </ruleImplementation>
      </childrenRules>
      <usesRules/>
      <ruleViolationMessage>Table without "WITH (NOLOCK)" hint used.</ruleViolationMessage>
      <ruleMatchType>ClassOnly</ruleMatchType>
      <violatingRulesCodeExamples>
        <RuleCodeExample>Select DistributorID, FirstName, LastName From dbo.Distributor D</RuleCodeExample>
      </violatingRulesCodeExamples>
      <compliantRulesCodeExamples>
        <RuleCodeExample>Select DistributorID, FirstName, LastName From dbo.Distributor D WITH (NOLOCK)</RuleCodeExample>
      </compliantRulesCodeExamples>
    </ruleImplementation>
  </rule>
</sql-rules>
