### ISSUE TITLE
Some sql files are not considerd by BaseTsqlSensor

### ISSUE THREAD

**Issue by rings777** [gretard/sonar-tsql-plugin#3]
Hi everyone,
in many projects the plugin works well but in one it does not work. The problem is related to some sql files.
Basically the impression is that some of them are not seen from SensorContext.Filestem.

More in detail, the BaseTsqlSensor Add method doesn't create the issue because the Inputfile is null. 
During the build, Sonar listed the sql files so i think that they are available into sensorContext.filesystem. It writes that found n issues but when the add method try to put together the cgresult issue with the sql section it fails.

When it try to create the issue, the InputFile file is null and the log returns "Could not find file blablabla to add issue blablabla at line blablabla.".

- I have checked that it's exported in UTF-8 format from Sql Server.
- I have added code to check file existence (e.g file.exists()) and it returns true.

What is wrong?

**Comment by gretard** [comment]
Hi, thank you for your issue. Will take a look. I see several places which might be causing issues, so could you provide more details with these?

- How are you running your scan - using sonar scanner command line tool or other means? 
- Maybe found issue line is 0 as currently plugin not supports it? Will try looking more into this. 
- Also, it would be interesting to know if only some particular issue type is causing this issue? 
- Does in sonar log with verbose logging those files are shown and detected as tsql language?

Greta

**Comment by rings777** [comment]
Hi, Greta. Thanks for the quick response. We have project under different source controls: TFS 2013 and TFS 2017. 

We run SQL Code Guard using a build custom step in TFS and SonarQube is invoked by automatic build too.

Our projects are developed in Visual Studio 2015

This is a simple project that we used to test SonarQube
The project structure is the following: (the directories are in Italic)
   _Src->_MyProject.sln
   _Src->MyProject_->*.cs, *.sql

SQL Code Guard is launched with those parameters:
   Sources = $(Build.SourcesDirectory)\MyProject
   Output = $(Build.SourcesDirectory)\MyProject\MyProjectcgresults.xml


We have checked but in line 0 there are no issues.

We have done test with standard plugin 0.2.0 and 0.3.5. we have recompiled the 0.2.0 TFS Plugin with additional logs to better understand the problem.

We have noticed that:
- We need to add .sql files into the c# solution to be listed into 'Source paths'. In this case the issues are created in SonarQube
- If they are not added to solution, but they are still under source control, sqlcodeguard add them into [myProject]cgresults.xml file but when the SqlCodeGuardIssuesLoaderSensor is processed it returns the error 'Could not find file..'.

Is it a requirement to have sql files into project?  Is it correct? We added the .SQL files to source control and we thought it was enough.

If this information can help, we have noticed another strange behavior, we have added a log into Execute BaseTsqlSensor to log the base dir. It seems to run twice with different base dirs:

In this case it works:
2017-05-23T08:00:01.6999601Z 10:00:01.653 INFO: Sensor SqlCodeGuardIssuesLoaderSensor (wrapped)
2017-05-23T08:00:01.6999601Z 10:00:01.653 DEBUG: QT - execute
2017-05-23T08:00:01.6999601Z 10:00:01.653 DEBUG: QT - get -  baseDir: C:\AgtBld10\_work\5\s\_MyProject_
2017-05-23T08:00:01.6999601Z 10:00:01.653 Added issue DEP013 on file C:/AgtBld10/_work/5/s/ MyProject /aaa.sql at line 25.

Note: -  baseDir: C:\AgtBld10\_work\5\s\_MyProject_ is the directory where the sql files are stored


2017-05-23T08:00:02.5124560Z 10:00:02.403 INFO: Sensor SqlCodeGuardIssuesLoaderSensor (wrapped)
2017-05-23T08:00:02.5124560Z 10:00:02.403 DEBUG: QT - execute
2017-05-23T08:00:02.5124560Z 10:00:02.403 DEBUG: QT - get -  baseDir: C:\AgtBld10\_work\5\s
2017-05-23T08:00:02.5124560Z 10:00:02.403 DEBUG: Could not find file C:\AgtBld10\_work\5\s\ _MyProject_ \ aaa.sql to add issue BP017 at line 35.

**Comment by Arturas-K** [comment]
Hi, 

@rings777 are you using new SonarQube extension from marketplace:
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube

Microsoft has transferred Sonar task maintenance to SonarQube team.
With this extension you get additional build step **SonarQube Scanner CLI**;
This is the step you need to use in order to get T-SQL analysis, msbuild tasks do not work with sqlproj projects at the moment.

Let us know if this helps.

**Comment by rings777** [comment]
Yes, we are using the new extensions from market place, the ones developed by sonarqube team. We are using ‘Prepare the SonarQube analysis’ and ‘Complete the SonarQube analysis’ steps.
We didn’t add sql files to a sqlproj but we added the sql files to a C# project:

![project](https://cloud.githubusercontent.com/assets/28801168/26352168/e1ff2804-3fba-11e7-9f6b-6c2649f738e7.png)

**Comment by gretard** [comment]
Hi, I think there are several options here:
 - If you are using the **Sonar start/stop analysis steps** - then you need to include those files into the project. 
- If you use **Sonar scanner cli** step, then you will not be needing to add those sql files into the project and they will be picked up by the scanner.
