### ISSUE TITLE
Issues not found

### ISSUE THREAD

**Issue by amali-zone** [gretard/sonar-tsql-plugin#4]
I have created a sample project and tried out this. But no issues were identified. Please help me. 

Sonar Version - 6.5 
[TSQL_Sample.zip](https://github.com/gretard/sonar-tsql-plugin/files/1292416/TSQL_Sample.zip)

**Comment by gretard** [comment]
Hello,

There could be multiple problems:
-  Rules are not activated in sonar
-  sonar.projectBaseDir=Stored Procedures - might be causing problems, please try to remove it as this is why microsoft issues are not displayed
- SQL code guard tool:
  - Is it installed onto your build machine?
  - Is the path correct in the sonar.tsql.cg.path? Also, seems that SQL code guard has been updated. Please see https://documentation.red-gate.com/display/SCG/Using+SQL+Code+Guard+command+line+or+MSBuild

Please let me know if this has helped :)

Greta

**Comment by amali-zone** [comment]
Yes it was due to rules were inactive. Thanks for the help.
