### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by amali-zone** [gretard/sonar-tsql-plugin#5]
Is there any possibility to define custom rules? 

E.g. Using cursors is defined as bad practice at my workplace. Therefore need to define a rule to detect cursors.

**Comment by gretard** [comment]
Hi,

Could you elaborate more on this? Do you have a tool which would be analyzing code and you want only to send reports to sonar for your custom rules? Or do you want plugin to parse your code and check if it does not violate any your custom rules?

Greta

**Comment by amali-zone** [comment]
I want plugin to do that. Something like search for some specific word and
report issues.

**Comment by gretard** [comment]
Hi,

Please see the latest release https://github.com/gretard/sonar-tsql-plugin/releases/tag/0.6.0-alpha1 and wiki at https://github.com/gretard/sonar-tsql-plugin/wiki/Custom-rules. Please let me know what issues you find :)

**Comment by amali-zone** [comment]
Thank you so much. I will evaluate this and give you feedback.
