### ISSUE TITLE
TSQL component not working with .sqlproj

### ISSUE THREAD

**Issue by cirotheodoro** [gretard/sonar-tsql-plugin#9]
Hi,

I've been using sonar-tsql-plugin to scan .sql files inside .sqlproj in SonarQube, but I'm not able too... in fact, if I add the same files to regular project class, then TSQL profiler is invoked... if I add the same files in .sqlproj, then it does not invoke TSQL profiler... is that correct? Inside a regular csproj I can see the following when running it:

15:40:12.299 DEBUG: 'Properties\AssemblyInfo.cs' indexed with language 'cs'
15:40:12.300 DEBUG: 'dbo.usp_dmssvc_Account_GetByMarket.sql' indexed with language 'tsql'
15:40:12.301 DEBUG: 'dbo.usp_dmssvc_Account_GetDetails.prc' indexed with language 'null'
15:40:12.301 INFO: 4 files indexed
15:40:12.302 INFO: Quality profile for cs: Sonar Optimized
**15:40:12.303 INFO: Quality profile for tsql: Sonar Way**

but this is not invoked when running the same procs inside a .sqlproj... any ideas?

**Comment by gretard** [comment]
Hi,

Could you provide more details - how are you running the analysis? Is it through TFS, if yes - then which step are you using? Or are you using sonar-scanner (https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) or other kind of scanner directly? 

Greta

**Comment by cirotheodoro** [comment]
Hi Greta,

I'm using Jenkins for that with the step:

SonarQube Scanner for MSBuild - Begin Analysis.

In the project and name I'm adding my project key and name in Sonar and in additional arguments I'm using:

/d:sonar.log.level=INFO
/d:sonar.verbose=true
/d:sonar.cs.vscoveragexml.reportsPaths=${WORKSPACE}\TestResults\coveragereport.xml
/d:sonar.cs.vstest.reportsPaths=${WORKSPACE}\TestResults\*.trx

... after that I have another Jenkins build step:

Build a Visual Studio project or solution using MSBuild
MSBuildVersion: 14.0
MSBuildFileName: <pathofsolution>
Command Line:
/nologo 
/p:Configuration=Release 
/verbosity:m 
/p:Platform="Any CPU"
/p:RunSqlCodeAnalysis=true
/p:OutDir="${WORKSPACE}\Binaries"

Does that help?

**Comment by gretard** [comment]
Hi,

Maybe you could try using sonar scanner for this? As I am not sure if Sonar's MSBuild scanner supports sql projects and need to look into this further :) Maybe you could build before running sonar scanner? 

Greta

**Comment by cirotheodoro** [comment]
Hi Greta,

I found an issue in one of the steps in Jenkins where it was deleting SQL files before sonar analysis ends. We removed it and it is working. Thanks for your help... however, still have one thing I'd like to ask you: I realized the plugin checked just .SQL files... is there a way to customize the file extension to analyze more type of files or we have a limitation on that today?

Thanks,
Ciro

**Comment by gretard** [comment]
Hello,

Custom files specification currently is not supported. However, this will be included in the next release.

Greta

**Comment by cirotheodoro** [comment]
Thank you,

Ciro

**Comment by gretard** [comment]
Hi, please see the latest release at https://github.com/gretard/sonar-tsql-plugin/releases/tag/0.6.2. Please let me know if there are any issues :) Configuration details can be found at wiki.
